codacy/chart

- .doks/doks-cluster/Makefile
This should temporarily get us rid of the hanging pvc/pod for listener-cache-claim while destroying the cluster.
> fix: removing hung codacy pods and pvcs before destroying cluster

- .circleci/config.yml
- .doks/Makefile
- .doks/doks-cluster/Makefile
the goal is to reduce the number of clusters and avoid conflicts between helm deployments running on the same cluster.
For example, the merge-to-dev and the hourly workflows will both point to the dev cluster. We do not want the hourly deployment interfering with what has been deployed to the same cluster.
> Use separate namespaces for dev and non-dev environments (release and nightly builds)

- docs/migration/database.md
This can happen when you specify the DB name and you have not created
the database prior to doing the restore operation
> Add note to create database if pg_restore fails

- .doks/Makefile
needs -n for namespace otherwise all rollout status commands fail.
> fix broken rotate pods

- .circleci/config.yml
- codacy/requirements.lock
- codacy/requirements.yaml
We want to go back to using regexes for versions.
The reason is that our hourly QA tests and hourly and nightly rollout validations will need to deploy the latest versions of each component to know whether there have been any breaking changes.
> fix: use semantic versions for all components

- .circleci/config.yml
By having a dedicated release branch, we can safely call update_versions on release as the versions on the requirements file will definitely be frozen versions :)
> fix: update worker version on release

- .circleci/config.yml
- codacy/requirements.lock
- codacy/requirements.yaml
This PR will allow us to push to the "hourly" namespace whenever a merge to master happens.
This PR will also bump the component versions for today's release.
The 'hourly' name is now quite misleading and we should revisit this asap (after the release).
> push to 'hourly' namespace on merge to master

- codacy/values.yaml
Because of this PR(https://bitbucket.org/qamine/codacy-website/pull-requests/2796/feature-use-engines-new-api/diff) on codacy-worker we now have a new value with the url for the engineApi.
> fix: Add missing config for engine api

- .circleci/config.yml
- .doks/Makefile
All workflows have a job to lint the chart so there is no point in linting the chart again on other jobs.
> refactor: remove duplicated lints

- .circleci/config.yml
- .doks/Makefile
we no longer need this.
by using --atomic we ensure that we only move forward with successful upgrades. If they fail, the cluster should be left in the previous successful helm upgrade.
> refactor: deprecate rotate pods with atomic + recreate pods

- .circleci/config.yml
Now that we are doing atomic upgrades, we know that the deployments will be left in a valid state whether the upgrade succeeds or fails.
Therefore, we should remove these validation jobs.
> refactor: remove validate deployments

- codacy/values.yaml
The fluentd operator was aggregating logs from all namespaces by default.
Since we have 3 installations of codacy in 3 different namespaces in the same cluster, this means that each fluentd operator would aggregate logs from the 3 different installations, which is not what we would like.
Following [this PR](https://github.com/codacy/kube-fluentd-operator/pull/5), we can set the value to only use the release namespace.
> fix: fluentd capture only the release namespace

- .circleci/config.yml
- requirements.pip
upload_docs started failing with:
`ERROR: mkdocs-material 4.6.0 has requirement markdown<3.2, but you'll have markdown 3.2 which is incompatible.`
https://circleci.com/gh/codacy/chart/7439
I have bumped the mk-docs patch version which seems to have fixed the issue on this branch.
> fix: fixing mkdocs material

- .doks/Makefile
With this PR, we can tell a specific component to only rotate its deployment when deploying to dev SH, instead of rotation all deployments.
> fix: default to all deployments on rotate pods

- codacy/requirements-dev.yaml
This will be required as we move forward with cloud == self-hosted for all components.
> refactor: use unstable versions on all components in req-dev.yaml

- .circleci/config.yml
This PR bumps the `codacy/base` orb version and uses a step in that orb to test installation of the chart to Microk8s in CircleCI in the new nightly pipeline.
Warning: includes breaking changes to workspace attachment
> bump: increase orb version and use micok8s to test install in CircleCI

- codacy/requirements-dev.yaml
- codacy/requirements.lock
- codacy/requirements.yaml
- codacy/templates/fluentd/fluentd-conf.yaml
TLDR:
After a long debug with the help of @DReigada we found that microk8s had no logs due to parsing issues.
The problem was basically that k8s writes logs in json while microk8s does not.
The parser is fluentd operator was not ready and needed some changes, which were already upstream in the vmware repo.
We issued a bump https://github.com/codacy/kube-fluentd-operator/pull/6 and it seems to work now.
Also two PRs were open: https://github.com/vmware/kube-fluentd-operator/pull/81 and https://github.com/vmware/kube-fluentd-operator/pull/104 to make sure we eventually remove the fork.
> Change log format and output [CY-1138]

- .circleci/config.yml
This doesn't seem to be needed anymore especially now that the loadbalancing is done through the codacy-ingress.
I could not find references/invocations of this job anywhere so it should be removed to make the config.yaml smaller and less confusing.
> refactor: remove unused job

- docs/extra/database.md
- docs/extra/k8s-cheatsheet.md
- docs/extra/uninstall.md
- docs/extra/upgrade.md
- mkdocs.yml
I'm adding an explicit navigation structure to the `mkdocs.yml` file so that the table of contents displayed on the sidebar of the generated pages follows the logical order of the installation instructions.
> Organize table of contents

- docs/extra/k8s-cheatsheet.md
If you do just `kubectl logs svc/<service-name>` you don't get the logs of every pod associated with the service. 
You can try with this example:
```yaml
apiVersion: v1
kind: Service
metadata:
name: hello-kubernetes
spec:
type: LoadBalancer
ports:
- port: 80
targetPort: 8080
selector:
app: hello-kubernetes
app2: another-label
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: hello-kubernetes
spec:
replicas: 3
selector:
matchLabels:
app: hello-kubernetes
template:
metadata:
labels:
app: hello-kubernetes
app2: another-label
spec:
containers:
- name: hello-kubernetes
image: debian
ports:
- containerPort: 8080
command: ["bin/bash"]
args: ["-c","while true; do sleep 3; echo \"hello from `hostname -i`\"; done"]
```
If you put this on a file called `test-logs.yaml`, do `kubectl apply -f …
> fix: get all logs associated with a service

- docs/infrastructure/microk8s-quickstart.md
- remove unnecessary command concatenation (e.g. ` && \`) -> better to fail at a specific point in case
- use snap to install helm (we already do it for microk8s good to be consistent)
- wait for microk8s only when needed
> fix: Improve the commands to install microk8s

- mkdocs.yml
This is necessary so that the new page appears on the table of contents sidebar of the generated HTML pages.
> Add bitbucket.md to the mkdocs.yaml navigation

- docs/configuration/git-providers/github-cloud.md
- docs/configuration/git-providers/github-enterprise.md
- docs/configuration/git-providers/gitlab-cloud.md
Apparently Codacy does not deal well with the value of this key unless
it's surrounded by quotes.
> Fix "enabled" value string

- docs/configuration/integrations/github-cloud.md
- docs/configuration/integrations/github-enterprise.md
When trying to use the `values-production.yaml` file with the private key using a multiline syntax the Helm upgrade fails:
```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character 20
at java.util.Base64$Decoder.decode0(Base64.java:714)
at java.util.Base64$Decoder.decode(Base64.java:526)
at java.util.Base64$Decoder.decode(Base64.java:549)
at com.codacy.remote.provider.service.configuration.utils.PrivateKeyLoader$.loadFromString(PrivateKeyLoader.scala:27)
at com.codacy.remote.provider.service.configuration.GitHubConfigurationFactory$$anonfun$apply$2.applyOrElse(GitHubConfiguration.scala:19)
at com.codacy.remote.provider.service.configuration.GitHubConfigurationFactory$$anonfun$apply$2.applyOrElse(GitHubConfiguration.scala:14)
at …
```
> Revert to asking users to remove newlines from their private keys

- codacy/values-microk8s.yaml
This config field was missing from the yaml.
I caught this while testing helm 3, which was complaining about the fact that `workerResources` was not a valid field. I went to check `worker-manager` and found out this discrepancy.
> fix: added missing config tag

- docs/requirements.md
Added the information that these ports are needed to allow access to the Codacy website and API endpoints.
> Add details in the notes for ports 80 and 443

- docs/requirements.md
To make it easier for customers to manage and configure their PostgreSQL database server, we are adding a more explicit recommendation of managed solutions for the main cloud providers.
> Improve recommendation to use managed PostgreSQL

- .circleci/config.yml
This is needed for the nightly builds with helm3
> feature: Bump codacy-orbs to have helm3

- .circleci/config.yml
The previous command was always returning 0.4.0 tag for unknown reasons.
With this change we fetch the latest tag (by creatordate) minus any RC tags.
> fix: changed git command that generates .version

- README.md
After the helm3 upgrade, both the cluste rname and some namespaces will have changed to a more standard nomenclature.
> fix: Update cluster entries on docs

- docs/infrastructure/microk8s-quickstart.md
Having each instruction as a numbered item helps the users keep track of the progress while following the instructions, and hopefully they are less likely to skip steps.
> style: Move kubeconfig export to explicit step

- .circleci/config.yml
It is only set on our values + makefile workflow, was not set for microk8s
> fix: Add crow url to the microk8s installation

- .circleci/config.yml
Updates helm to 3.2.1 that has some bug fixes
> bump: Update ci-do to the latest version

- docs/index.md
- docs/infrastructure/microk8s-quickstart.md
- docs/maintenance/uninstall.md
- docs/requirements.md
- docs/troubleshoot/k8s-cheatsheet.md
This brings back the changes reverted by <https://github.com/codacy/chart/pull/422> , which postponed until our stable version supports Helm v3.
> Feature: Upgrade docs to Helm v3

- docs/infrastructure/microk8s-quickstart.md
Moved the Helm requirement to the section "Prepare your environment".
This is to avoid having to maintain instructions on how to install Helm. However, if we understand that customers need a bit more guidance we can go back to having more "step by step instructions" on how to install all the necessary tools.
> Remove explicit Helm install commands from MicroK8s quickstart guide

- .do/Makefile
Using a relative jsonpath expression leads to problems when doing the rollout restart for statefulsets.
> fix: Monitoring resources rollout

- .do/values.yaml
- docs/configuration/monitoring.md
With helm3 if service monitors are enabled deployment fails with the following error:
```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(ServiceMonitor.spec.selector): unknown field "app.kubernetes.io/instance" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector, ValidationError(ServiceMonitor.spec.selector): unknown field "app.kubernetes.io/name" in com.coreos.monitoring.v1.ServiceMonitor.spec.selector]
```
I'm reverting this for now until we find a workaround and fix the components' servicemonitor templates.
> fix: Revert servicemonitor creation due to prometheus operator helm3 issues

- docs/maintenance/upgrade.md
I'm reviewing the instructions on how to upgrade Codacy using Helm 3.
I (hopefully) fixed a couple of issues, namely:
* The fact that the namespace was not specified (I cannot tell for sure from the [Helm documentation](https://helm.sh/docs/helm/helm_get_values/#options-inherited-from-parent-commands) if this is required or not...)
* The output format for `helm get values` was not specified and the [default](https://helm.sh/docs/helm/helm_get_values/#options) would be `table`.
I need a validation that this is indeed the correct way of upgrading Codacy using Helm 3.
> Edit instructions on how to upgrade the Helm release

- codacy/values.yaml
Services should really not be opinionated on what port they run on. That should
be configured when deploying on a specific environment. Since the service Crow
no longer assumes in its configurations on what ports some services are running,
we need to specify that here.
See https://bitbucket.org/qamine/crow/pull-requests/163/explicitly-set-sslmode-when-connecting-to
> fix: Add port value for certain services

- docs/configuration/integrations/bitbucket-cloud.md
- docs/configuration/integrations/bitbucket-server.md
- docs/configuration/integrations/email.md
- docs/configuration/integrations/github-cloud.md
- docs/configuration/integrations/github-enterprise.md
- docs/configuration/integrations/gitlab-cloud.md
- docs/configuration/integrations/gitlab-enterprise.md
- docs/configuration/monitoring.md
- docs/troubleshoot/troubleshoot.md
The flag is deprecated in Helm 3.
See https://v3.helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
for more information. To maintain the functionality in Helm 3, it's required to make a change to the Helm template.
In this pull request I already removed the deprecated flag from the documentation, but the remaining changes are still pending.
> fix: Remove deprecated flag --recreate-pods

- .do/values.yaml
- docs/configuration/monitoring.md
This enables the service monitors in our dev environments, now that this has been upgraded in the components and won't cause validation errors when installed with helm3. This also uncomments the grafana+prometheus monitoring stack documentation because this becomes feasible and relevant again.
> feature: enable service monitors

- .circleci/config.yml
Currently visiting the root of our docs show an older version of them. With this PR we are setting `latest` as the default docs, which then causes a redirection of the root to `latest` (see [here](https://github.com/jimporter/mike#setting-the-default-version) for more info).  I tested locally and it worked correctly.
> fix: Redirect docs root to latest version

- .circleci/config.yml
I'm deleting the following line that would "reset" the default docs version:
`mike set-default latest -m "[ci skip] Updated default documentation version" -p`
In practice, what this command does is (re)creating the `index.html` file at the root of the `gh-pages` branch with a small JavaScript to redirect to the `latest` path:
```javascript
window.location.replace("latest");
```
However, I had to update this JavaScript so it also takes into account anchor links and makes the appropriate redirections:
```javascript
(function () {
var newPath = "latest/";
var hash = window.location.hash.substring(1);
if (hash) {
window.location.replace(newPath + "#" + hash);
} else {
window.location.replace(newPath)
}
})();
```
By removing the `mike set-default [...]` we ensure that my fix is not reverted on …
> Avoid resetting the default doc version

- docs/js/version-select.js
This updates the script `version-select.js` with the original one provided by mike, but with a small change to use another known CSS file to infer the base URL of the documentation.
(See details here: https://github.com/jimporter/mike/pull/19)
> fix: Update version-select.js to correctly infer base URL

- docs/index.md
According to @heliocodacy there's no longer a step during the onboarding flow where the administration account is created.
Could the reviewers please help validate this?
> doc: Remove creating admin account step

- docs/configuration/tls-ingress.md
Fixed incorrect Markdown syntax and typo in the name of the Let's Encrypt service.
> doc: Fix malformed link to Let's Encrypt

- codacy/values-production.yaml
- docs/maintenance/license.md
- mkdocs.yml
Currently we do not have instructions on how customers should set or update their production license.
I'm adding a placeholder on the `values-production.yaml` configuration file for setting the production license at installation time, as well as a short page explaining how the license can be updated at a later time.
**Note to self:** when this PR is merged I need to include a link to these instructions on the [page about enabling submodules](https://github.com/codacy/docs/pull/78).
> doc: Add instructions on how to set and update the Codacy license

- codacy/values.yaml
Add new engine api port to config - we can change this through config in cloud, but we were not exposing this in SH
> fix: add port to new engine api configs CY-1536

- codacy/values-production.yaml
- codacy/values.yaml
We should set this to a known value, to prevent errors on redeployment (cf. [here](https://github.com/helm/charts/tree/master/stable/rabbitmq-ha#upgrading-the-chart)). When merging this the new value for the erlangcookie will be different from the pre-existing one in our cluster so we'll need to delete the pvcs to ensure smooth deployment.
> fix: set rabbitmq erlang cookie to prevent redeployment errors

- mkdocs.yml
This is to ensure that the path for the chart documentation on docs.codacy.com is lowercase (https://docs.codacy.com/chart/), making it consistent with all the other pages.
(This is in preparation to remove the old GitHub Pages site containing the chart documentation - https://codacy.atlassian.net/browse/DOCS-97)
> doc: Rename site name from Chart to lowercase chart

- docs/configuration/integrations/bitbucket-cloud.md
- docs/configuration/integrations/gitlab-cloud.md
- docs/configuration/integrations/gitlab-enterprise.md
- docs/index.md
- docs/troubleshoot/troubleshoot.md
This is to make the markup consistent to the one described in the documentation for the extension, as the previous markup was also working correctly:
https://python-markdown.github.io/extensions/attr_list/
> doc: Correct Attribute Lists markup

- docs/configuration/integrations/github-app-create.md
We were providing only the webhook URL for GitHub Cloud but not GitHub Enterprise.
> Provide GitHub Enterprise webhook URL when creating GitHub App

- docs/troubleshoot/troubleshoot.md
Removes the spurious section **Lost or changed database secrets** (that had been removed in #458), and edits the instructions on how to access the RabbitMQ dashboard.
> doc: Edit troubleshooting instructions

- .circleci/config.yml
- requirements.pip
The idea is to do a quick build of the docs using `mkdocs build` just to check if something is broken. Otherwise, we will only know about issues when we build the docs on the [codacy/docs](https://github.com/codacy/docs) repository side.
> feature: Check if docs build successfully on every commit

- docs/index.md
Currently, Helm 3.3 is not compatible with MinIO.
Even though we are stating that customers should use Helm 3.2, we're adding a notice to make it explicit that Helm 3.3 will not work.
> doc: Add Helm 3.3 known incompatibility notice

- README.md
The old URLs for these two charts now include deprecation notices pointing to the new repositories.
> fix: Update MinIO and PostgreSQL chart links

- .changelogs/gitchangelogtemplate.rc
This shall only get merged after the current ongoing release.
> fix: Disable Merge messages on changelogs.

- docs/index.md
Drop incompatibility warning and support Helm versions >= 3.2.
The new version 1.6.0 should fix the incompatibility with MinIO and we can now support Helm 3.3 as well.
@joaocosta-codacy, since these changes apply to the new 1.6.0 release, we will need to cherry pick the changes to the branch `release-1.6.0`.
> Update supported Helm version

- .do/values.yaml
This should fix having issues with deploy rabbitmq prometheus rules.
We should now end up with one rabbitmq related prometheusrule object per development environment.
> fix: deploy prometheus rules per namespace

- docs/configuration/integrations/bitbucket-cloud.md
- docs/configuration/integrations/bitbucket-server.md
- docs/configuration/integrations/email.md
- docs/configuration/integrations/github-cloud.md
- docs/configuration/integrations/github-enterprise.md
- docs/configuration/integrations/gitlab-cloud.md
- docs/configuration/integrations/gitlab-enterprise.md
- docs/configuration/monitoring.md
- docs/configuration/tls-ingress.md
- docs/index.md
- docs/maintenance/license.md
- docs/troubleshoot/k8s-cheatsheet.md
- mkdocs.yml
- requirements.pip
I'm renaming the branch originally created for #553 because the single quotes [caused issues on the CI/CD workflows](https://app.circleci.com/pipelines/github/codacy/chart/4134/workflows/0a34214f-864b-4073-92f5-8ce9c96d6e9a/jobs/18486).
> doc: Fix chart version when running helm upgrade

- Makefile
- codacy/values.yaml
This is the companion of:
https://bitbucket.org/qamine/codacy-website/pull-requests/3837/feature-add-an-api-endpoint-to-return-the
to inject the full version of the codacy installation.
> feature: Full version of Codacy

- docs/infrastructure/eks-quickstart.md
Small edits:
* Move the introduction of the diagram before the image.
* Limit the size of the image to 1024 pixels wide
* Fix typo in image alternative text
> doc: Edit introduction to Amazon EKS diagram

- docs/index.md
The sample output obtained by getting information about the pods included the `codacy-core` pod, which will no longer exist in future releases of the chart.
> doc: Remove core pod from example output CY-2490

- .circleci/config.yml
This will bring the latest changes to the orb in https://github.com/codacy/codacy-orbs/pull/118
Microk8s tests should run successfully regardless of having the old base users
> bump: codacy-orbs to include fix for removing base users CY-1441

- codacy/templates/fluentd/fluentd-conf.yaml
Deleted:
* kubernetes.host
* kubernetes.container_image_id
* kubernetes.pod_name
* kubernetes.container_name
> fix: Delete additional fields from fluentd output

- RELEASE.md
This is just a small improvement to avoid having people copy paste the examples and release a version 6.0.0 by mistake.
> docs: Change release examples to have a 'safer' version number

- docs/configuration/integrations/gitlab-enterprise.md
The URI appeared correctly in the example screenshot but not on the instruction step.
Thanks to @heliocodacy for reporting this. :+1:
> Add missing redirect URI when configuring GitLab Enterprise

- docs/configuration/integrations/gitlab-cloud.md
The URI appeared correctly in the example screenshot but not on the instruction step.
This is the same issue that was fixed on #581, but for GitLab Cloud (we only noticed the issue after merging the previous pull request).
> Add missing redirect URI when configuring GitLab Cloud

- docs/configuration/integrations/github-app-create.md
Fixes https://github.com/codacy/docs/issues/201.
When configuring a new GitHub App, we now ask the user to explicitly disable the setting **Expire user authorization tokens**.
> doc: Disable "Expire user authorization tokens" while creating GitHub Apps

- RELEASE.md
As a way to give more visibility to the release notes for each new chart version, it's a good idea to add a link to the public release notes page on each new version. For example: https://github.com/codacy/chart/releases/tag/2.1.1
I'm adding a step to the release process to manually add a link to the release notes page. But perhaps this step could be automated, as the URL of the release notes can be easily built by taking the new version number into account.
> doc: Add step to link GitHub release with release notes page

- codacy/values-production.yaml
We removed the TLS setup documentation on https://github.com/codacy/chart/pull/560, but the `values-production.yaml` file still referenced the documentation for more information on how to perform the configuration.
> fix: Remove TLS setup annotations from values-production.yaml

- docs/troubleshoot/extract-codacy-logs.sh
This updates a URL that was still pointing to the old chart documentation address.
> fix: Update documentation URL in extract-codacy-logs.sh

- .circleci/config.yml
- RELEASE.md
This will also post the release notes link in the body of the release.
All that is left to do is provision the CIRCLECI_GITHUB_TOKEN with a relevant github user from our org for this to work.
> feature: Added job to automate release creation

- RELEASE.md
This avoids errors if multiple tags exist locally.
> docs: Improve git push tag example

- .circleci/config.yml
- .gitignore
- Makefile
- RELEASE.md
Currently we are setting the version for the documentation. Since the `.version` file is only created during the circleci worflow.
This makes it so that we generate the version locally when running the `make prepare_release` command
> fix: Use correct version for documentation

- docs/index.md
The installation documentation did not explicitly mention that it applies to Codacy Self-hosted. Although this is obvious to us, it may not be obvious for inexperienced users.
> doc: Edit page title to mention Codacy Self-hosted

- docs/releasenotes.md
Since this file is not referenced in `mkdocs.yml`, MkDocs outputs a warning when generating the documentation.
> doc: Remove spurious and empty file releasenotes.md

- docs/maintenance/uninstall.md
- docs/troubleshoot/k8s-cheatsheet.md
The offending command removes all PVs in the cluster since PVs are not bound to a specific namespace.
More information on Slack:
https://codacy.slack.com/archives/C8X9SS1H7/p1602489596000800
> doc: Remove command that wrongly deletes all PVs in the cluster

- RELEASE.md
Links the RELEASE.md to the overview of the process to generate release notes on the Handbook.
> doc: Add link to release notes process in Handbook

- codacy/templates/fluentd/fluentd-conf.yaml
We can not use this with our fluentd version. 
`reloader time="2020-10-16T10:44:54Z" level=info msg="Configuration for namespace codacy-dev cannot be validated: bad tag for <filter>: kubernetes.var.log.containers.**codacy-dev**. Tag must start with **, $thisns or codacy-dev"`
A new ticket has been raised to address this issue
> fix: fluentd namespace resolution

- .circleci/config.yml
This cherry-picks the fixes from release 2.2.1
> feature: Add aws credentials to qa job tests

- README.md
- docs/troubleshoot/k8s-cheatsheet.md
Since these instructions are useful when developing Codacy, it makes more sense to include them directly in the README.md of the repository than in the [customer-facing documentation](https://docs.codacy.com/chart/troubleshoot/k8s-cheatsheet/).
For more information, see the Slack discussion: https://codacy.slack.com/archives/C8X9SS1H7/p1604403487009700
> doc: Move how to install a custom Codacy version to README.md

- .circleci/config.yml
- .gitignore
- Makefile
- RELEASE.md
If no .version file exists, one should be created.
This should address the issue of cutting releases from a local machine, when no .version file exists.
> fix: Changed documentation version process

- README.md
Adds documentation on the path to override the repositoriesLimit value.
Default 100 that comes from the repo, we don't want to change this number.
This is an added option for really slow repositories list before the next improvements.
Configuration already live in prod at https://github.com/codacy/codacy-spa/blob/dev/.helm/codacy-spa/values.yaml#L76
It felt that it could fit under the "config", but now it seems a bit different from the other components, let me know what you guys think
> Add repositoriesLimit to the documentation

- RELEASE.md
This is needed if you have a garbage .version from previous releases
> docs: Update make command to remove the .version file

- docs/troubleshoot/logs-collect.md
It wasn't clear for a customer where the command that collected the logs should run:
https://codacy.slack.com/archives/CQESXTUHW/p1609956509001900
Besides clarifying this, I also reorganized the page to make the main procedure of collecting logs simpler, and placing all information related to the potential size of the archive being too big at the bottom inside a note:
> clean: Refactor and improve "Collecting logs for Support"

- codacy/values.yaml
Replace trial license key with a new one, valid for the same amount of users (4) and expiring in the end of 2030
> fix: update trial license

- docs/requirements.md
- docs/troubleshoot/logs-collect.md
- docs/troubleshoot/troubleshoot.md
Fixes incorrect syntax of link to Support email address, and simplifies the Markdown syntax for all email links.
> doc: Fix mailto: link syntax

- docs/requirements.md
Reverts the update made to MicroK8s in https://github.com/codacy/chart/pull/662.
See this Slack thread for more context:
https://codacy.slack.com/archives/CSSSHAK9N/p1613129943008100?thread_ts=1612965786.001800&cid=CSSSHAK9N
> fix: Revert maximum supported MicroK8s version

- .gitignore
- Makefile
- RELEASE.md
See [DOCS-129](https://codacy.atlassian.net/browse/DOCS-129) for more information.
I decided to rename the repository containing the tools related to release notes generation to `codacy-tools-release-notes` as it is a bit more tidy and consistent with the naming of other Codacy repositories.
> clean: Rename repository containing release notes tools DOCS-129

- Makefile
This change is needed to make https://github.com/codacy/codacy-tools-release-notes/pull/29 work.
> feature: Include chart version when calling release notes script DOCS-204

- README.md
Fixes a broken table in the README:
> doc: Fix broken table in README

- docs/infrastructure/EKS/main/cluster_masters.tf
There is an error in the log_group name, which implies the retention policy isn't applied to the cluster log_group, causing the logs to accumulate over time.
> fix[eks]: Use the cluster name in the log_group name

- docs/maintenance/upgrade.md
The relative URL starting at the root passed unnoticed under the MkDocs tests (as intended), but made the validation of the links on the generated HTML fail:
https://github.com/codacy/docs/commit/e31b809428f9ab7b5eedac60a80fb36376c3bfbe
> fix: Update relative URL to absolute

- Makefile
The docs generation should rely on the current .lockfile if the dependencies are updated again, the .lockfile is going to be overriden.
Also, needs to force pulling the tags, as they are usually overriden upstream (like the latest tag)
> fix: Don't update components versions on docs generation

- docs/requirements.md
@h314to, is there anything else we need to do before including this newer PostgreSQL version in the Codacy Self-hosted requirements? And should we recommend version 10.15 or 10.14?
> doc: Update supported PostgreSQL version

- docs/configuration/integrations/email.md
This is to avoid having two pages with the same title because of the change in https://github.com/codacy/docs/pull/671.
I decided not to change the actual filename for this page so that we don't have to deal with broken links. 🔗
> doc: Change title of "Emails" to "SMTP server" DOCS-253

- docs/maintenance/upgrade.md
This uses a variable that contains the chart version/tag for the current documentation version, for example, `3.5.1`.
I believe it's best to have the version explicit [on the documentation](https://docs.codacy.com/chart/maintenance/upgrade/), as customers can always change the version or remove the flag `--version` completely if they wish.
This makes the instructions more explicit / safer for the cases when we release patches or minor versions out of the usual "version order".
> doc: Fix chart version when upgrading Codacy Self-hosted

- RELEASE.md
It's no longer necessary to manually open a pull request while generating the release notes since this is done automatically by the makefile target.
See https://github.com/codacy/codacy-tools-release-notes/pull/41.
> doc: Simplify instructions on how to generate release notes DOCS-50

- RELEASE.md
Small edit to simplify the section [Approval by the Technical Writer](https://github.com/codacy/chart/blob/master/RELEASE.md#approval-by-the-technical-writer) in `RELEASE.md`.
> doc: Simplify Technical Writer approval process during release

- Makefile
Adds the new command `selfhosted` to specify generating release notes for Codacy Self-hosted:
https://github.com/codacy/codacy-tools-release-notes#generating-codacy-self-hosted-release-notes
(See https://github.com/codacy/codacy-tools-release-notes/pull/49 for more information.)
> clean: Update Makefile target get_release_notes DOCS-269

- docs/configuration/integrations/github-app-create.md
Even though the page on [how to create a GitHub App](https://docs.codacy.com/chart/configuration/integrations/github-app-create/) already included the indication to disable the option **Expire user authorization tokens**, we've been finding that some customers configure this option incorrectly.
This pull request adds a note to call the attention of customers to this setting:
> doc: Highlight disabling expiring tokens

- Makefile
Necessary changes to take into account the renaming of the repository codacy/codacy-tools-release-notes to the shorter and simpler name [codacy/release-notes-tools](https://github.com/codacy/release-notes-tools).
> clean: Update release-notes-tools repository name

- .gitignore
I missed this update on https://github.com/codacy/chart/pull/697.
> fix: Update release notes repository name in .gitignore

- RELEASE.md
Releasing a new version of the documentation is necessary to ensure that customers have access to the documentation that is in sync with their Codacy Self-hosted version:
> doc: Mention publishing a new docs version in RELEASE.md

- .circleci/config.yml
This fixes the issues causing deployment pipeline failures.
> bump: Upgrade ci-do image

- docs/index.md
- docs/maintenance/upgrade.md
Adds the notices below to the Codacy Self-hosted installation and upgrade documentation to help catch scenarios where customers may be using the legacy solution running on Docker or using legacy manual organizations.
Let me know if you think this is enough or if you feel we need something even more visible/explicit.
> feature: Add notices regarding drop of legacy organizations in 5.0.0

- docs/infrastructure/eks-quickstart.md
The previous URL is now redirecting to the new page specific for Version 1.
Fixes https://github.com/codacy/docs/issues/989.
> doc: Update link for AWS CLI Version 1

- .circleci/config.yml
Needed because of CircleCI base images deprecation
> bump: Bump codacy/base orb

- docs/maintenance/upgrade.md
Small improvement to help customers navigate more quickly to the relevant release notes.
> doc: Point release notes link directly to Self-hosted releases

- RELEASE.md
Adds an explicit step at the beginning of the release process to clarify the scope of new Codacy Self-hosted versions with the Product team.
https://github.com/codacy/chart/blob/doc/clarify-release-scope/RELEASE.md
> doc: Update release process to clarify scope of new versions

- mkdocs.yml
This configuration is necessary to enable Edit buttons directly on the documentation pages, see https://github.com/codacy/docs/pull/1140.
> doc: Add repository information to mkdocs.yml

- RELEASE.md
Currently, the step to create a pull request with the automatically generated release notes can go a bit unnoticed [at the very end of section 2](https://github.com/codacy/chart/blob/master/RELEASE.md#2-preparing-the-release-for-testing) of the release process.
I propose that generating the release notes become the first step of section 3, and that the Release Manager uses the release notes pull request to help communicate to stakeholders that a new Self-hosted release candidate is available for validation.
https://github.com/codacy/chart/blob/doc/update-release-notes-process/RELEASE.md#3-testing-and-stabilizing-the-release
> doc: Highlight release notes generation by moving step to section 3

- docs/infrastructure/eks-quickstart.md
Updates the broken link to the [last documentation version](https://registry.terraform.io/providers/hashicorp/aws/2.70.1/docs#shared-credentials-file) that mentions the `AWS_SDK_LOAD_CONFIG=1` configuration.
Fixes https://github.com/codacy/docs/issues/1191.
> doc: Update broken link to Terraform docs

- docs/configuration/integrations/github-app-create.md
Fixes https://github.com/codacy/docs/issues/1241.
> doc: Update link to moved page on GitHub documentation

- Makefile
- codacy/requirements-dev.yaml
- codacy/requirements.yaml
Bitnami has unexpectedly changed the retention policy for its charts repo, causing versions for the rabbitmq and postgresql charts we require to be missing. This PR uses the historical index for the bitnami, which includes the missing charts.
See [this issue](https://github.com/bitnami/charts/issues/10539) for further details.
> fix: Use historical bitnami repo

- docs/configuration/integrations/gitlab-enterprise.md
[CY-6117](https://codacy.atlassian.net/browse/CY-6117) introduced support for expiring access tokens, meaning that the users no longer have to disable that option (in GitLab Enterprise versions that include it).
> doc: Remove disabling expiring access tokens for GitLab Enterprise CY-6117

- docs/infrastructure/eks-quickstart.md
The URL fragment no longer exists on the target page.
> doc: Update broken link

- docs/configuration/integrations/bitbucket-server.md
In the context of [CY-6251](https://codacy.atlassian.net/browse/CY-6251) we added support for configuring the context path of Bitbucket Server instances.
> doc: Add Bitbucket Server context path configuration CY-6251

- docs/configuration/integrations/gitlab-cloud.md
The GitLab Cloud setup instructions still include a note stating that Codacy doesn't support expiring access tokens because it wasn't removed in https://github.com/codacy/chart/pull/735 by mistake.
> doc: Remove disabling expiring access tokens for GitLab Cloud CY-6117

- README.md
- docs/configuration/caching.md
- docs/configuration/integrations/bitbucket-server.md
- mkdocs.yml
Adds instructions on how to configure Codacy Self-hosted to mount an NFS volume on an external server.
https://feature-update-chart--docs-codacy.netlify.app/chart/configuration/caching/
> doc: Add external NFS setup instructions DOCS-393

- docs/requirements.md
Bumps the required PostgreSQL version to the latest 10.x minor version.
For extra context, see [this Slack thread](https://codacy.slack.com/archives/CAL88HZL6/p1657549644016559).
> doc: Bump required PostgreSQL version

- .circleci/config.yml
- codacy/requirements-dev.yaml
- codacy/requirements.yaml
- codacy/values.yaml
- docs/index.md
- docs/requirements.md
This PR introduces some version updates and some compatibility fixes for more recent versions of k8s, namely:
- Bumps helm version used in testing to latest stable.
- Bumps orb version to add fixes that make microk8s deployment in ci less flaky.
- Test by default using the current stable version of helm and k8s 1.21.
- Add tests with microk8s 1.22, as a first step towards officially supporting this version.
- Drops support for deprecated k8s versions, those earlier than 1.19 (already not supported by cloud providers)
- Updates version information on our docs about k8s and helm.
> fix: deploy to k8s 1.22

- codacy/values-production.yaml
- codacy/values.yaml
This change is just to put what is currently configured live, as code, since there was a mismatch.
This prevented the deployment to complete, because helm was trying to patch a PersistentVolumeClaim with a value smaller than what's currently there (so 40Gi configured to 20Gi as code) and Kubernetes does not allow that.
The screenshot shows the current values we have live, which as you can confirm match the change in this PR
> fix: Update minio storage persistence to match value in cluster

- .do/db-cluster/config.tf
- .do/k8s-cluster/variables.tf
Also bumped the providers version on DO files.
This was not possible to do on k8s files without further changes, because the current configuration was not compatible.
Want to discuss of those required changes are worth doing right now.
> bump: Upgrade terraform providers and k8s cluster version

- docs/troubleshoot/troubleshoot.md
Adds a troubleshooting section for the error "Upgrade failed: cannot patch "codacy-minio" while upgrading to Codacy Self-hosted 9.0.0 with an updated `codacy-production.yaml` file.
Fixes #754.
https://github.com/codacy/chart/blob/doc/troubleshoot-minio-storage-DOCS-449/docs/troubleshoot/troubleshoot.md#upgrade-failed-cannot-patch-codacy-minio
> doc: Troubleshoot upgrade with new MinIO PVC size DOCS-449

- docs/configuration/integrations/github-app-create.md
Adds the mandatory option "Request user authorization (OAuth) during installation" to the values table on [Creating a GitHub App](https://docs.codacy.com/chart/configuration/integrations/github-app-create/) page.
> feat: Add option Request user authorization during installation DOCS-457

- .github/CODEOWNERS
Adds the GitHub group @codacy/techwriters as CODEOWNERS of the `/docs/` directory.
> doc: Add @codacy/techwriters as /docs/ CODEOWNERS

- docs/infrastructure/eks-quickstart.md
Adds updated instructions for installing the NGINX Ingress Controller when using Kubernetes 1.22 or later. 
https://github.com/codacy/chart/blob/doc/update-nginx-install-DOCS-521/docs/infrastructure/eks-quickstart.md#5-install-the-nginx-ingress-controller
> doc: Update NGINX Ingress Controller install for K8s >=1.22 DOCS-521

- RELEASE.md
Updates an outdated link to the internal docs describing the release notes process.
> doc: Update link to release notes process

- Makefile
This update reflects the changes from https://github.com/codacy/release-notes-tools/pull/129.
> clean: Use master branch of release-notes-tools

- Makefile
This reverts the changes from the pull request #778.
See https://github.com/codacy/release-notes-tools/pull/130 for more details.
> Revert "doc: Update link to release notes process"

- docs/values-files/values-loki.yaml
- docs/values-files/values-promtail.yaml
PodSecurityPolicy was deprecated in k8s 1.25 [REL-1308](https://codacy.atlassian.net/browse/REL-1308), therefore we need to explicitly disable them for loki and promtail.
[REL-1308]: https://codacy.atlassian.net/browse/REL-1308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Disable loki and promtail deprecated psp [REL-1308]

- docs/infrastructure/microk8s-quickstart.md
- docs/requirements.md
* Updates microk8s installation instructions with step on disabling the high-availability option
* Extends supported k8s versions to 1.24
> doc: Update v11 documentation DOCS-570

- docs/maintenance/database.md
- docs/requirements.md
* Updates supported Kubernetes versions to `1.22.* to 1.26.* (1.23 recommended)`
* Updates supported PostgreSQL versions to `version 11.20 or version 12.* (12.* recommended)`
* Updates links to external PostgreSQL documentation to version 12 (recommended version)
> doc: SH 13 documentation updates

- .circleci/config.yml
Trying to increase Selenium Grid driver's timeouts since it seems that the sessions are timing out too early, making the auto tests fail.
> feature: Increase Selenium Grid driver's timeouts
