.gitignore
quickstart/aks/README.md
quickstart/aks/backend/config.tf
quickstart/aks/backend/outputs.tf
quickstart/aks/backend/state_and_lock.tf
quickstart/aks/backend/variables.tf
quickstart/aks/main/auth.tf
quickstart/aks/main/cluster.tf
quickstart/aks/main/config.tf
quickstart/aks/main/outputs.tf
quickstart/aks/main/variables.tf
quickstart/aks/setup/config.tf
quickstart/aks/setup/constants.tf
quickstart/aks/setup/helm_charts.tf
quickstart/aks/setup/kubernetes.tf
quickstart/aks/setup/outputs.tf
quickstart/aks/setup/roles.tf
quickstart/aks/setup/templates/cert-manager-crds.yaml
quickstart/aks/setup/variables.tf

The documentation for the AKS quickstart is still very basic, but deployment/destruction works more or less like for EKS (apart from the cli setup, which is itself very simple). I'm pushing this to the repo in the hope it will be useful to others, and we'll iterate on this later.

feature: Add AKS quickstart

---

.circleci/config.yml

Opened a new pr as a fast-forward merge from dev didn't get signed in the old feature branch.

feature: added hourly workflow against dev branch

---

.circleci/config.yml

hourly pipeline no longer pushes to chartmuseum. 
nightly pipeline pushes only to nightly channel

fix: helm publications on workflows

---

README.md

fix: Fix README images

---

codacy/requirements.yaml

At the time of writing this comment this version of `ragnaros` is not yet published. 
Please wait for a comment saying that this is good to merge before doing so

fix: evolutions for results2017 FT-6848

---

.circleci/config.yml
.doks/Makefile

fix: replace recreate pods with kubectl commands

---

README.md
codacy/requirements.yaml
codacy/values-production.yaml

Please wait for worker-manager 8.11.2 to be published. I'll comment in this PR when it is ready

fix: remove results references and bump wm

---

.circleci/config.yml

fix: remove commit and tag of lock file

fix: no longer commit nor tag requirements.lock on nightly workflow

---

codacy/requirements.lock
codacy/requirements.yaml
codacy/values.yaml

DO NOT MERGE YET!
This is still waiting for promoting the worker-manager and worker to stable.
Will write back in this PR when it is done

bump: new versions for components and resultsdb key fix

---

.doks/Makefile

Hoping that this shines some light into why the nightlies intermittently fail with an Unauthorized error from digital ocean

Bubble up any error from doctl set context

---

.circleci/config.yml

With this we can ensure that the clusters are up and running with tiller (specific version) installed

feature: ensure clusters are started on workflows

---

.circleci/config.yml

Deleting code is always fun :-D

refactor: remove nightly in favour of using microk8s clusters

---

.circleci/config.yml
.circleci/getChangelogs.sh
.doks/Makefile
.doks/values.yaml
Makefile
RELEASE.md

ci: makefile update_dependencies as a wrapper for all updates

release process v3

---

codacy/values-production.yaml

Found a typo that causes pod failure if not corrected

Update values-production.yaml to fix Hotspots DB typo

---

.doks/Makefile
.doks/values.yaml
.remarkrc
codacy/values.yaml
docs/infrastructure/microk8s-quickstart.md
docs/install.md

I tried to clarify what are the actual values that the user must use to configure Ingress - hostnames of the Codacy application and API endpoint instead of "DNS" entries.

Improve Ingress configuration documentation

---

docs/install.md

This is just to fix the Markdown syntax that was breaking the page install.md:
https://codacy.github.io/chart/install/

Fix Markdown formatting on install.md

---

.editorconfig
README.md
docs/configuration/extract-codacy-logs.sh
docs/configuration/logging.md

To improve the life of our K8s clients, a log extraction script was created.
The script also compacts the logs using `zip`.
Ideally this script will be short live since one of two things happen:
* A UI is created to log extraction
* Selfhosted K8s and MicroK8s will include a data pipeline platform (such as
ELK), where logs will be available.

docs: Add log extraction script [CY-1140]

---

.circleci/config.yml

I forgot to remove this test job when i merged the sandbox branch for the new changelogs.

refactor: remove changelogs on sandbox

---

.doks/values.yaml
codacy/values.yaml

refactor: disable postgres on non digital ocean

---

docs/requirements.md

Fix spurious values for the recommended number of replicas per component in MicroK8s clusters.

Fix replicas in component for MicroK8s

---

codacy/values-production.yaml

I have apparently left crow's configuration for prod incomplete. Apologies.
This PR should put all the required values in values-production for crow to work out of the box.

fix: add values for crow in prod

---

docs/requirements.md

Fixing the number of replicas as discussed during the "Training on K8s" meeting.

Fix number of replicas for recommended MicroK8s

---

docs/index.md
docs/infrastructure/microk8s-quickstart.md

Applying feedback to the documentation resulting from the user test with @caxaria on 2020-04-09.
Notes available here:
https://codacy.atlassian.net/browse/https://codacy.atlassian.net/browse/CY-1170

docs: Apply user feedback CY-1170

---

docs/requirements.md

Added the networking requirements as identified in this issue:
https://codacy.atlassian.net/browse/DOCS-34
This was also identified while doing this user test:
https://codacy.atlassian.net/browse/CY-1170

Add networking requirements

---

docs/configuration/secrets/extract-codacy-secrets.sh
docs/configuration/secrets/troubleshoot.md
docs/extra/extract-codacy-logs.sh
mkdocs.yml

Related to https://bitbucket.org/qamine/codacy-website/pull-requests/3379/wip-feature-move-secrets-value-to-logs-cy

feature: Add secrets troubleshooting [CY-1336]

---

RELEASE.md
docs/index.md
docs/infrastructure/microk8s-quickstart.md
docs/requirements.md

We might want to change the AKS and EKS specific documentation as well.
@pauloribeiro-codacy this is the base where we feel it is important to change, feel free to make it nicer if you find the ways 😸

feature: Update general documentation to prefer helm3 REL-337

---

docs/infrastructure/microk8s-quickstart.md

We have found this to be a requirement for installing codacy on microk8s with helm3.

fix: Updated docs on kubeconfig for helm3 install

---

.circleci/config.yml
codacy/templates/fluentd/fluentd-conf.yaml
codacy/templates/fluentd/lifecycle-police-job.yaml

Tested in sandbox using https://github.com/codacy/chart/tree/sandbox/revert-fluentpolicy and it fixed the issue.

revert: Change from fluentd creating s3 policy to manually creating policy with deployment hook

---

RELEASE.md

Added missing steps for cherry-picking fixes from master into the release.
Added missing steps for involving Solutions Engineers in the release process.

feature: Updated release docs.

---

.do/values.yaml
README.md
codacy/values-production.yaml
codacy/values.yaml

Following this pr: https://bitbucket.org/qamine/%7Bc7d54495-59e1-47b3-b4c0-c93b4c6bd45f%7D/pull-requests/813

feature: Add worker inactivity timeout CY-1780

---

.circleci/config.yml

This way we have an explicit step that should clarify where we are in the release process.

feature: Add manual approval from solutions eng.

---

RELEASE.md

Some revisions for the current release process:
- Add first step to communicate to engineering 
- Fix links
- Add separate QA and Sol. Engineers approval steps
- Add cherry-picking in patch

Docs: revisions of the release process from release 1.1.0

---

.circleci/config.yml
.do/Makefile

Sandbox should remain the same.

feature: deploy infrastructure to dev.

---

.do/values.yaml

Revert "fix: Rabbit defaults"

---

codacy/values-production.yaml
docs/configuration/monitoring.md
docs/index.md

This is to address a few comments received from a customer that went through the installation process. In particular:
> I'm following the instructions here: https://codacy.github.io/chart/latest/#2-installing-codacy
> 
> On step 6 it says:
> 
> If you are using MicroK8s you must use the file values-microk8s.yaml together with the file values-production.yaml.
> Use wget to download the extra file and uncomment the last line before running the helm upgrade command below:
> wget https://raw.githubusercontent.com/codacy/chart/master/codacy/values-microk8s.yaml
> 
> However there are no commented lines in values-microk8s.yaml or values-production.yaml. Can I ignore that?
> 
> Also, I need to fill in values for the following, but I don't know where to get them:
> 
> <--- crow-login-password …

doc: Apply small tweaks based on customer feedback

---

docs/configuration/monitoring.md

This pull request aims to address the issue that affected a customer and that is described here:
https://codacy.slack.com/archives/CAL88HZL6/p1595935172004300
🚧 Depends on https://github.com/codacy/chart/pull/522 being merged

doc: Add disclaimer to service dashboards DOCS-96

---

.circleci/config.yml

Bumps terraform version to 0.13.2

breaking: ci-do image

---

docs/infrastructure/microk8s-quickstart.md
docs/requirements.md

This is related to the 1.16 upgrade by @h314to
He recommends also adding some clarifications about our supported and recommended versions of K8s/microk8s

update: microk8s version in docs

---

codacy/values.yaml

Fixes https://bitbucket.org/qamine/portal/pull-requests/757/release

fix: Remove engineApi configs

---

.circleci/config.yml
.gitignore
Makefile
RELEASE.md

This doesn't fix the documentation version for the normal release flow, since the first commit of a release won't be tagged.

Revert docs version fix

---

codacy/values.yaml

we need this because the default ports are bleeding from one subchart to another: helm/helm#8298

make port numbers fixed

---

Makefile

You might need to run 'helm repo remove stable' to remove
the old one from your helm repos

fix: Add the correct helm repo

---

docs/values-files/values-nginx.yaml

In order to prevent the ingress to ingress controller starvation

Add resources limits to the nginx controller

---

docs/requirements.md

This pull request updates the [requirements documentation](https://docs.codacy.com/chart/requirements/#cluster-hardware-requirements) with a few improvements identified in [DOCS-154](https://codacy.atlassian.net/browse/DOCS-154).

doc: Clarify requirements regarding resource allocation and concurrent analysis

---

docs/configuration/monitoring.md
docs/infrastructure/eks-quickstart.md
docs/infrastructure/microk8s-quickstart.md
docs/requirements.md

Fixes broken links detected in codacy/docs#367.

fix: Update broken links

---

docs/requirements.md

:construction: This pull request must only be merged after https://github.com/codacy/docs/pull/341 is merged.

feature: Mention supported Git providers in system requirements

---

docs/requirements.md

Fixes broken link identified in codacy/docs#399.

fix: Update broken link

---

RELEASE.md

Introduce subsection for pulling fixes from components without changing affected components

docs: improve documentation for the release process

---

codacy/values-production.yaml

Most clients get the indentation of the integration section wrong without intervention. This should improve their success rate with SE help

Update integration indentation

---

docs/configuration/integrations/bitbucket-cloud.md
docs/configuration/integrations/bitbucket-server.md
docs/configuration/integrations/email.md
docs/configuration/integrations/github-app-create.md
docs/configuration/integrations/github-cloud.md
docs/configuration/integrations/github-enterprise.md
docs/configuration/integrations/gitlab-cloud.md
docs/configuration/integrations/gitlab-enterprise.md
docs/configuration/monitoring.md
docs/index.md
docs/infrastructure/eks-quickstart.md
docs/infrastructure/microk8s-quickstart.md
docs/maintenance/database.md
docs/maintenance/license.md
docs/maintenance/uninstall.md
docs/maintenance/upgrade.md
docs/requirements.md
docs/troubleshoot/k8s-cheatsheet.md
docs/troubleshoot/logs-collect.md
docs/troubleshoot/troubleshoot.md

Add meta descriptions or improve the introduction paragraphs of each documentation page, necessary to complete codacy/docs#585.

doc: Add meta descriptions to documentation pages DOCS-227

---

docs/index.md
docs/infrastructure/eks-quickstart.md
docs/infrastructure/microk8s-quickstart.md

Review and curate the meta descriptions of the [top landing pages for Google searches](https://docs.google.com/spreadsheets/d/191E8aGjiJwpSp8sroPZQUeZMmSiJ7t2HHLFGnJvkhEE/edit#gid=566714567).

doc: Improve meta descriptions of top searched pages DOCS-227

---

RELEASE.md

This is a batch of small edits and tweaks to the release process that resulted from the pairing that @pedrocodacy and I did to start the release of the new Codacy Self-hosted version 4.0.0.
You can preview the changes on the following link:
https://github.com/codacy/chart/blob/doc/improve-release-instructions/RELEASE.md#1-deciding-to-release-a-new-version

clean: Small edits and improvements to the release process

---

docs/configuration/integrations/github-cloud.md
docs/configuration/integrations/github-enterprise.md

Users have been leaving the Begin/End sections in their private key and causing integration failures. I've update the docs, but would like input on the wording to be as clear as possible

doc: Update Github .pem file instructions

---

docs/configuration/integrations/github-cloud.md
docs/configuration/integrations/github-enterprise.md

This was a suggestion that wasn't included in https://github.com/codacy/chart/pull/687.

doc: Edit instructions for GitHub App privateKey field

---

docs/infrastructure/eks-quickstart.md

This is a tiny cosmetic tweak, see https://github.com/codacy/docs/pull/754.

doc: Make bolds in simulated dts consistent

---

docs/infrastructure/eks-quickstart.md

Fixes https://github.com/codacy/docs/issues/756.

doc: Update broken link for VPC subnet tagging

---

docs/infrastructure/eks-quickstart.md

Detected on https://github.com/codacy/docs/issues/1042

doc: Fix broken links to Terraform documentation

---

docs/maintenance/upgrade.md

See also https://github.com/codacy/docs/pull/1065.

docs: Add step for updating the command-line tools to tagged version DOCS-355

---

docs/configuration/integrations/gitlab-cloud.md
docs/configuration/integrations/gitlab-enterprise.md

For more details see [this Slack thread](https://codacy.slack.com/archives/C8X9SS1H7/p1648034220923219).

doc: Add instructions to disable expiring access tokens on GitLab

---

docs/configuration/integrations/bitbucket-server.md
docs/configuration/integrations/github-app-create.md
docs/configuration/logging.md
docs/index.md

See [DOCS-145](https://codacy.atlassian.net/browse/DOCS-145) for details on this decision.

doc: Always open links on the same window DOCS-145

---

docs/troubleshoot/troubleshoot.md

Mention explicitly in the title that the troubleshooting page applies to Codacy Self-hosted.

doc: Update title of "Troubleshooting Codacy"

---

docs/requirements.md

See [DOCS-505](https://codacy.atlassian.net/browse/DOCS-505) for background information on this change.
[DOCS-505]: https://codacy.atlassian.net/browse/DOCS-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

doc: Clarify why some pods require privileged mode DOCS-505

---

docs/requirements.md

See [this internal Slack thread](https://codacy.slack.com/archives/C011BCR2RN3/p1684339582142419) for more context.

doc: Reduce range of supported MicroK8s versions

---

.do/values-promtail.yaml

Related to DO k8s upgrade to 1.25 [REL-1308](https://codacy.atlassian.net/browse/REL-1308)
[REL-1308]: https://codacy.atlassian.net/browse/REL-1308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: promtail configuration

---

docs/configuration/caching.md
docs/configuration/integrations/bitbucket-cloud.md
docs/configuration/integrations/bitbucket-server.md
docs/configuration/integrations/email.md
docs/configuration/integrations/github-cloud.md
docs/configuration/integrations/github-enterprise.md
docs/configuration/integrations/gitlab-cloud.md
docs/configuration/integrations/gitlab-enterprise.md
docs/configuration/logging.md
docs/configuration/monitoring.md
docs/index.md
docs/maintenance/license.md
docs/maintenance/upgrade.md

See https://github.com/codacy/docs/pull/1743 for more information.

doc: Rename MkDocs variable for keeping the current Self-hosted version

---

codacy/values.yaml

This is to reduce the diff of the SH release

style: Format values.yaml

---

.circleci/config.yml

Increased jvm memory for test runs

test: Increase memory to run tests

---

.do/k8s-cluster/Makefile

This reflects what was manually inputed in the digital ocean console.

feature: Set k8s min nodes to 1

---

docs/infrastructure/eks-quickstart.md
docs/values-files/values-nginx.yaml

Fix for vulnerabilities:
- https://nvd.nist.gov/vuln/detail/CVE-2022-4886
- https://nvd.nist.gov/vuln/detail/CVE-2023-5043
- https://nvd.nist.gov/vuln/detail/CVE-2023-5044

doc: Nginx vulnerabilities fix

---

.circleci/config.yml

Migrate to report portal new instance.
Related to [REL-1421](https://codacy.atlassian.net/browse/REL-1421)
[REL-1421]: https://codacy.atlassian.net/browse/REL-1421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: Migrate RP

---

.circleci/config.yml

[CY-7236](https://codacy.atlassian.net/browse/CY-7236)
[CY-7236]: https://codacy.atlassian.net/browse/CY-7236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bump: codacy orb 11.0.0

---

docs/maintenance/license.md

Adds the procedure to check the Codacy license expiry date.

doc: Add procedure to check expiry date DOCS-664

---

docs/requirements.md

Update supported and recommended K8S versions

doc: SH14 doc updates DOCS-674

---

.circleci/config.yml

https://codacy.atlassian.net/browse/REL-1655

bump: Update helm to 3.16.3

---

.do/k8s-cluster/values/values-nginx.yaml

https://codacy.atlassian.net/browse/REL-1720

fix: error in chart due to 1.29 bump
